
STANDARD_DEVIATION_OF_EXECUTE_TIME = 0 # 0.1
STANDARD_DEVIATION_OF_DATA_SIZE = 0 # 0.1
MAX_VM_IDLE_TIME = 2200
BAND_WIDTH = 1000000

WORKFLOW_NUM = 10
ARRIVAL_LAMBDA = 0.1
DEADLINE_FACTOR = 2.0

DEBUG = False

def PrintConfig():
    print("WORKFLOW_NUM : ", WORKFLOW_NUM)
    print("ARRIVAL_LAMBDA : ", ARRIVAL_LAMBDA)
    print("STANDARD_DEVIATION_OF_EXECUTE_TIME : ", STANDARD_DEVIATION_OF_EXECUTE_TIME)
    print("STANDARD_DEVIATION_OF_DATA_SIZE : ", STANDARD_DEVIATION_OF_DATA_SIZE)
    print("DEADLINE_FACTOR : ", DEADLINE_FACTOR)
    print()